import crypto from "crypto";
import { promises as fs } from "fs";
import path from "path";

/**
 * Per-client referral codes. Deterministic from the client id + a stored
 * secret, so the same client always has the same 6-char code without us
 * having to persist one. Codes are checked against the existing coupons
 * table when a new client redeems — on valid redemption, the referrer
 * gets a thank-you coupon (generated by the caller).
 */

const SECRET_FILE = path.join(process.cwd(), "data", "secret.json");

type Secret = { referralCodeSecret?: string };

async function readSecret(): Promise<Secret> {
  try {
    return JSON.parse(await fs.readFile(SECRET_FILE, "utf-8")) as Secret;
  } catch {
    return {};
  }
}

async function writeSecret(s: Secret): Promise<void> {
  await fs.mkdir(path.dirname(SECRET_FILE), { recursive: true });
  await fs.writeFile(SECRET_FILE, JSON.stringify(s, null, 2), "utf-8");
}

async function loadSecret(): Promise<string> {
  const s = await readSecret();
  if (s.referralCodeSecret && s.referralCodeSecret.length >= 16) {
    return s.referralCodeSecret;
  }
  const fresh = crypto.randomBytes(16).toString("hex");
  await writeSecret({ ...s, referralCodeSecret: fresh });
  return fresh;
}

/**
 * Uppercase, human-safe 6-char code. Avoids confusable characters (0/O, 1/I).
 */
function toBase28(bytes: Buffer, len: number): string {
  const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // 32 chars, no 0/O/1/I
  let out = "";
  for (let i = 0; i < len; i++) {
    out += ALPHABET[bytes[i] % ALPHABET.length];
  }
  return out;
}

export async function referralCodeForClient(clientId: string): Promise<string> {
  const secret = await loadSecret();
  const h = crypto.createHmac("sha256", secret).update(clientId).digest();
  return "REF-" + toBase28(h, 6);
}

/**
 * Reverse lookup: given a submitted code, find the client id that generated
 * it. We don't store codes — we just iterate the known clients and recompute.
 * (Fine up to a few thousand clients; at larger scale we'd cache or persist.)
 */
export async function resolveReferralCode(
  code: string,
  allClientIds: string[]
): Promise<string | null> {
  const normalized = code.trim().toUpperCase();
  if (!/^REF-[A-Z2-9]{6}$/.test(normalized)) return null;
  for (const id of allClientIds) {
    if ((await referralCodeForClient(id)) === normalized) return id;
  }
  return null;
}
